export const galleryTypes = [
  "winter namdas",
  "quilts",
  "wall hangings",
  "matress",
  "bed covers",
  "tea sheets",
  "dressing tools",
  "curtain tracks",
  "roman blinds",
  "zebra blinds",
  "blankets",
  "floor blankets",
  "pillows",
  "cushions",
  "cushion cover",
  "bed sheets",
  "bedding",
  "towels",
  "rugs",
  "foam",
  "runners",
  "rubber matting",
  "pvc",
  "curtains",
  "masjid carpets",
  "carpets",
  "carpet rolls",
  "wall to wall",
  "pray carpets",
];